name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_on_ubuntu:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node_version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: see directory
        run: ls
      - run: npm install
      - run: npm run build
      - run: ls
      - run: ls lib
